import React from "react";
import { ArrowRight, BookOpen, CheckCircle2, Compass, Play, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { usePersonalLearning } from "../../components/learning/PersonalLearningProvider";

export const PersonalCourseDashboard: React.FC = () => {
  const { currentCourse, loading } = usePersonalLearning();
  const navigate = useNavigate();
  const { i18n } = useTranslation();
  const uk = !i18n.language?.startsWith("en");
  if (loading) return <div className="mx-auto max-w-6xl px-4 py-16 text-sm text-[#718078]">{uk ? "Завантажуємо навчальний простір…" : "Loading your learning space…"}</div>;
  if (!currentCourse) return <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-10"><div className="rounded-[28px] border border-[#00c875]/25 bg-[#0d2519] p-8 text-white sm:p-12"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#00d782]/15 text-[#53eea5]"><Compass /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-[#53eea5]">{uk ? "Твій навчальний простір" : "Your learning space"}</p><h1 className="mt-3 max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl">{uk ? "Обери перший курс і почни свій маршрут." : "Choose your first course and start your path."}</h1><p className="mt-4 max-w-xl text-base leading-7 text-[#b7d1c0]">{uk ? "Курс об’єднає теорію, практику та прогрес в одному послідовному потоці." : "A course brings theory, practice, and progress into one continuous flow."}</p><button type="button" onClick={() => navigate("/learning/catalog")} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#eff7f1] px-5 py-3 font-bold text-[#122219]">{uk ? "Відкрити каталог" : "Browse courses"}<ArrowRight className="size-4" /></button></div></section>;
  const next = currentCourse.nextAction;
  const items = currentCourse.modules.flatMap((module) => module.items.map((item) => ({ ...item, moduleTitle: module.title }))).slice(0, 5);
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-10 lg:py-12">
    <section className="rounded-[28px] border border-[#00c875]/25 bg-[#0d2519] p-7 text-white shadow-[0_24px_70px_-42px_rgba(0,200,117,.7)] sm:p-10">
      <div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#53eea5]"><Sparkles className="size-4" />{uk ? "Поточний курс" : "Current course"}</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">{currentCourse.title}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[#b7d1c0]">{currentCourse.description || (uk ? "Послідовний маршрут із теорії та практики." : "A focused path through theory and practice.")}</p></div><div className="min-w-[220px] rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between text-sm font-semibold"><span>{uk ? "Загальний прогрес" : "Overall progress"}</span><span>{Math.round(currentCourse.enrollment.completionPercent)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#00d782]" style={{ width: `${currentCourse.enrollment.completionPercent}%` }} /></div><p className="mt-3 text-xs text-[#9eb9a8]">{currentCourse.modules.length} {uk ? "модулів у маршруті" : "modules in your path"}</p></div></div>
      <div className="mt-9 flex flex-wrap gap-3"><button type="button" onClick={() => next ? navigate(`/learning/course/${currentCourse.id}/practice/${next.itemId}`) : navigate(`/learning/course/${currentCourse.id}/path`)} className="inline-flex items-center gap-2 rounded-xl bg-[#eff7f1] px-5 py-3 font-bold text-[#122219]"><Play className="size-4 fill-current" />{next ? (uk ? "Продовжити навчання" : "Continue learning") : (uk ? "Переглянути маршрут" : "View path")}<ArrowRight className="size-4" /></button><button type="button" onClick={() => navigate(`/learning/course/${currentCourse.id}/path`)} className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 font-semibold text-[#e1f1e6]">{uk ? "Відкрити маршрут" : "Open path"}</button></div>
    </section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-[24px] border border-[#152219]/10 bg-white p-6 dark:border-white/[.09] dark:bg-[#111a14]"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#00b96b]">{uk ? "Наступні кроки" : "Next steps"}</p><h2 className="mt-2 text-2xl font-bold">{next?.title || (uk ? "Курс завершено" : "Course completed")}</h2></div><BookOpen className="size-5 text-[#00c875]" /></div><div className="mt-6 space-y-3">{items.map((item) => <button key={item.id} type="button" onClick={() => navigate(`/learning/course/${currentCourse.id}/${item.kind === "CODE_TASK" || item.kind === "WEB_TASK" ? `practice/${item.id}` : "path"}`)} className="flex w-full items-center gap-4 rounded-2xl border border-[#152219]/8 p-4 text-left transition hover:border-[#00c875]/40 hover:bg-[#f5faf6] dark:border-white/[.08] dark:hover:bg-white/[.03]"><span className={`flex size-9 shrink-0 items-center justify-center rounded-xl ${item.progress.status === "COMPLETED" ? "bg-[#dff8e8] text-[#00a85f] dark:bg-[#00d782]/10" : "bg-[#eef3ef] text-[#6f7f74] dark:bg-white/[.06]"}`}>{item.progress.status === "COMPLETED" ? <CheckCircle2 className="size-4" /> : <span className="text-xs font-bold">{item.order}</span>}</span><span className="min-w-0 flex-1"><span className="block truncate font-semibold">{item.title}</span><span className="mt-1 block truncate text-xs text-[#75847a]">{item.moduleTitle}</span></span><ArrowRight className="size-4 shrink-0 text-[#829087]" /></button>)}</div></div><div className="rounded-[24px] border border-[#152219]/10 bg-[#f3f7f3] p-6 dark:border-white/[.08] dark:bg-[#101a13]"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#00b96b]">{uk ? "Курсова активність" : "Course activity"}</p><h2 className="mt-2 text-2xl font-bold">{uk ? "Ти рухаєшся послідовно" : "You are moving steadily"}</h2><p className="mt-3 text-sm leading-6 text-[#65756a] dark:text-[#aab9ae]">{uk ? "Усі спроби в цьому просторі належать курсу. Вільна практика в Lab залишається окремо." : "Everything here belongs to this course. Free practice in Lab stays separate."}</p><button type="button" onClick={() => navigate(`/learning/course/${currentCourse.id}/progress`)} className="mt-8 inline-flex items-center gap-2 font-semibold text-[#009f5b]">{uk ? "Переглянути прогрес" : "View progress"}<ArrowRight className="size-4" /></button></div></section>
  </main>;
};
