name = "studycod-ai-worker"
main = "src/index.ts"
compatibility_date = "2025-12-24"

# Workers AI binding
ai = { binding = "AI" }

[vars]
ENVIRONMENT = "development"

[env.production]


[env.production.vars]
ENVIRONMENT = "production"
