import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowRight, BookOpen, Check, ChevronRight, CircleDot, FileText, Gauge, GraduationCap, Inbox, LayoutDashboard, Library, Mail, MessageSquare, Plus, Send, Settings2, ShieldCheck, Sparkles, UserRoundPlus, Users, Wrench, X } from "lucide-react";
import {
  approveAdminLibraryTask,
  createAdminUser,
  disableAdminMaintenance,
  enableAdminMaintenance,
  getAdminClasses,
  getAdminJudgeLoad,
  getAdminLibraryTasks,
  getAdminMailStatus,
  getAdminMaintenance,
  getAdminMaterialTopics,
  getAdminStats,
  getAdminSupportConversations,
  getAdminUsers,
  rejectAdminLibraryTask,
  sendAdminBroadcastEmail,
  type AdminClass,
  type AdminJudgeLoad,
  type AdminLibraryTask,
  type AdminMaterialTopic,
  type AdminStats,
  type AdminSupportChatConversation,
  type AdminUser,
  type MaintenanceState,
} from "../../lib/api/admin";
import { listCertificateTemplates } from "../../lib/api/certificates";

const preview = () => import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "true";

type Tab = "overview" | "people" | "content" | "support" | "maintenance" | "broadcast" | "mailbox" | "certificates";
const tabs: Array<{ id: Tab; label: string; Icon: React.ComponentType<{ className?: string }> }> = [
  { id: "overview", label: "Огляд", Icon: LayoutDashboard },
  { id: "people", label: "Люди", Icon: Users },
  { id: "content", label: "Контент", Icon: Library },
  { id: "support", label: "Підтримка", Icon: MessageSquare },
  { id: "maintenance", label: "Maintenance", Icon: Wrench },
  { id: "broadcast", label: "Розсилки", Icon: Send },
  { id: "mailbox", label: "Mailbox", Icon: Inbox },
  { id: "certificates", label: "Сертифікати", Icon: FileText },
];

const Surface: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = "" }) => <section className={`rounded-[24px] border border-[#152219]/10 bg-white p-5 shadow-[0_18px_42px_-36px_rgba(10,36,18,.5)] dark:border-white/10 dark:bg-[#121b15] ${className}`}>{children}</section>;
const Label: React.FC<{ children: React.ReactNode; tone?: string }> = ({ children, tone = "text-[#147b47] dark:text-[#62ecaa]" }) => <div className={`text-xs font-semibold uppercase tracking-[.16em] ${tone}`}>{children}</div>;

export const AdminWorkspacePage: React.FC = () => {
  const navigate = useNavigate();
  const [tab, setTab] = useState<Tab>("overview");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [stats, setStats] = useState<AdminStats | null>(null);
  const [judge, setJudge] = useState<AdminJudgeLoad | null>(null);
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [classes, setClasses] = useState<AdminClass[]>([]);
  const [topics, setTopics] = useState<AdminMaterialTopic[]>([]);
  const [library, setLibrary] = useState<AdminLibraryTask[]>([]);
  const [conversations, setConversations] = useState<AdminSupportChatConversation[]>([]);
  const [maintenance, setMaintenance] = useState<MaintenanceState | null>(null);
  const [mailOk, setMailOk] = useState<boolean | null>(null);
  const [certificates, setCertificates] = useState<Array<{ id: number; name: string; isActive: boolean }>>([]);
  const [libraryStatus, setLibraryStatus] = useState<"PENDING" | "APPROVED" | "REJECTED" | "DRAFT">("PENDING");
  const [busyId, setBusyId] = useState<number | null>(null);
  const [showCreateUser, setShowCreateUser] = useState(false);
  const [newUser, setNewUser] = useState<{ username: string; email: string; password: string; role: "USER" | "TEACHER" | "SYSTEM_ADMIN"; userMode: "PERSONAL" | "EDUCATIONAL" | "CONTEST"; lang: "JAVA" | "PYTHON" | "CPP" }>({ username: "", email: "", password: "", role: "USER", userMode: "PERSONAL", lang: "PYTHON" });
  const [broadcast, setBroadcast] = useState({ subject: "", title: "", content: "" });
  const [broadcastResult, setBroadcastResult] = useState<string | null>(null);

  const load = async () => {
    setLoading(true); setError(null);
    if (preview()) {
      setStats({ users: { total: 1840, teachers: 86 }, classes: { total: 57 } } as AdminStats);
      setJudge({ active: 4, queued: 7 } as AdminJudgeLoad);
      setUsers([{ id: 1, username: "oksana", firstName: "Оксана", email: "oksana@example.test", role: "USER" }, { id: 2, username: "iryna.teacher", firstName: "Ірина", email: "iryna@example.test", role: "TEACHER" }, { id: 3, username: "admin", firstName: "Admin", email: "admin@example.test", role: "SYSTEM_ADMIN" }] as AdminUser[]);
      setClasses([{ id: 1, name: "Python 10-Б", teacherName: "Ірина Кравець" }, { id: 2, name: "Algorithms 11-А", teacherName: "Олена Романюк" }] as AdminClass[]);
      setTopics([{ id: 1, order: 1, title: "Змінні та типи", theoryBlock: { version: 3 } }, { id: 2, order: 2, title: "Умови", theoryBlock: null }] as AdminMaterialTopic[]);
      setLibrary([{ id: 11, title: "Сума парних", lang: "PYTHON", status: "PENDING", author: { username: "mentor-anna" } }] as AdminLibraryTask[]);
      setConversations([{ id: 1, subject: "Не відкривається урок", userEmail: "student@example.test", status: "OPEN", lastMessageAt: new Date().toISOString() }] as AdminSupportChatConversation[]);
      setMaintenance({ enabled: false, title: "", message: "", until: null, updatedAt: new Date().toISOString() } as MaintenanceState);
      setMailOk(true); setCertificates([{ id: 1, name: "StudyCod achievement", isActive: true }, { id: 2, name: "Summer contest", isActive: false }]); setLoading(false);
      return;
    }
    try {
      if (tab === "overview") {
        const [nextStats, nextJudge, state, mail, templates] = await Promise.all([
          getAdminStats(), getAdminJudgeLoad().catch(() => null), getAdminMaintenance().catch(() => null), getAdminMailStatus().catch(() => null), listCertificateTemplates({ includeInactive: true, limit: 8 }).catch(() => null),
        ]);
        setStats(nextStats); setJudge(nextJudge); setMaintenance(state?.state ?? null); setMailOk(mail?.ok ?? null); setCertificates((templates?.templates ?? []).map((item) => ({ id: item.id, name: item.name, isActive: item.isActive })));
      }
      if (tab === "people") { const [nextUsers, nextClasses] = await Promise.all([getAdminUsers({ page: 1, limit: 100 }), getAdminClasses()]); setUsers(nextUsers.users); setClasses(nextClasses.classes); }
      if (tab === "content") { const [nextTopics, nextLibrary] = await Promise.all([getAdminMaterialTopics({ language: "PYTHON" }), getAdminLibraryTasks({ status: libraryStatus })]); setTopics(nextTopics.topics); setLibrary(nextLibrary.tasks); }
      if (tab === "support") { const next = await getAdminSupportConversations(); setConversations(next.conversations); }
      if (tab === "maintenance") { const state = await getAdminMaintenance(); setMaintenance(state.state); }
      if (tab === "mailbox") { const mail = await getAdminMailStatus(); setMailOk(mail.ok); }
      if (tab === "certificates") { const templates = await listCertificateTemplates({ includeInactive: true, limit: 30 }); setCertificates((templates.templates ?? []).map((item) => ({ id: item.id, name: item.name, isActive: item.isActive }))); }
    } catch (cause: any) { setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося завантажити дані.")); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [tab, libraryStatus]);

  const createUser = async (event: React.FormEvent) => { event.preventDefault(); setError(null); try { await createAdminUser(newUser); setShowCreateUser(false); setNewUser({ username: "", email: "", password: "", role: "USER", userMode: "PERSONAL", lang: "PYTHON" }); await load(); } catch (cause: any) { setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося створити користувача.")); } };
  const moderate = async (task: AdminLibraryTask, action: "approve" | "reject") => { setBusyId(task.id); try { if (action === "approve") await approveAdminLibraryTask(task.id); else await rejectAdminLibraryTask(task.id, "Потрібне доопрацювання перед публікацією."); await load(); } catch (cause: any) { setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося оновити задачу.")); } finally { setBusyId(null); } };
  const toggleMaintenance = async () => { try { const next = maintenance?.enabled ? await disableAdminMaintenance() : await enableAdminMaintenance({ title: "Планове оновлення", message: "Ми виконуємо коротке оновлення сервісу.", until: null }); setMaintenance(next.state); } catch (cause: any) { setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося оновити maintenance.")); } };
  const sendBroadcast = async (event: React.FormEvent) => { event.preventDefault(); setBroadcastResult(null); try { const result: any = await sendAdminBroadcastEmail({ ...broadcast, audience: "ALL", delivery: "NOTIFICATION", dryRun: true }); setBroadcastResult(`Dry run: ${result?.count ?? 0} recipients`); } catch (cause: any) { setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося підготувати розсилку.")); } };
  const usersByRole = useMemo(() => ({ teachers: users.filter((user) => user.role === "TEACHER").length, admins: users.filter((user) => user.role === "SYSTEM_ADMIN").length }), [users]);

  return <div className="min-h-full bg-[#f7f8f5] px-4 py-7 text-[#142017] dark:bg-[#0b120e] dark:text-[#edf3ef] sm:px-6 lg:px-10 lg:py-10"><div className="mx-auto max-w-[1480px]">
    <section className="relative overflow-hidden rounded-[28px] bg-[#20232a] px-6 py-7 text-white shadow-[0_24px_58px_-36px_rgba(0,0,0,.8)] sm:px-8 sm:py-9"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#ffd93d]/10 blur-3xl" /><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><Label tone="text-[#ffd93d]"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4" />System administration</span></Label><h1 className="mt-4 font-[family-name:var(--font-display)] text-3xl font-bold tracking-[-.055em] sm:text-5xl">Керуй платформою без хаосу.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#c3c9d0]">Реальні дані, модерація, сервісні операції та комунікація — у спільному робочому контексті.</p></div><button onClick={() => navigate("/?app=home")} className="rounded-xl border border-white/15 bg-white/8 px-4 py-3 text-sm font-semibold text-white transition hover:bg-white/13">Вийти до продукту</button></div></section>
    <nav className="mt-5 flex gap-1.5 overflow-x-auto rounded-2xl border border-[#152219]/10 bg-white p-2 dark:border-white/10 dark:bg-[#121b15]">{tabs.map(({ id, label, Icon }) => <button key={id} onClick={() => setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-semibold transition ${tab === id ? "bg-[#17251c] text-white dark:bg-[#edf3ef] dark:text-[#0b120e]" : "text-[#6a796f] hover:bg-[#f1f5f1] dark:text-[#a6b5aa] dark:hover:bg-white/[.06]"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
    {error && <div className="mt-5 flex items-center justify-between gap-4 rounded-2xl border border-[#ff6b9d]/30 bg-[#fff1f5] p-4 text-sm text-[#be315c] dark:bg-[#ff6b9d]/10 dark:text-[#ffabc4]"><span>{error}</span><button onClick={() => setError(null)}><X className="h-4 w-4" /></button></div>}
    {loading ? <div className="mt-5 grid gap-4 md:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-40 animate-pulse rounded-[24px] bg-[#e6ece7] dark:bg-white/[.045]" />)}</div> : <div className="mt-5">
      {tab === "overview" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric value={stats?.users.total ?? "—"} label="користувачів" /><Metric value={stats?.users.teachers ?? "—"} label="викладачів" tone="text-[#147b47] dark:text-[#62ecaa]" /><Metric value={stats?.classes.total ?? "—"} label="активних класів" /><Metric value={judge?.queued ?? "—"} label="у черзі judge" tone="text-[#d97706]" /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Surface><Label>Стан системи</Label><div className="mt-5 grid gap-3 sm:grid-cols-2"><Status label="Judge queue" value={judge ? `${judge.active} active · ${judge.queued} queued` : "Немає даних"} healthy={(judge?.queued ?? 0) < 20} /><Status label="Maintenance" value={maintenance?.enabled ? "Увімкнено" : "Платформа відкрита"} healthy={!maintenance?.enabled} /><Status label="Admin mailbox" value={mailOk === null ? "Немає даних" : mailOk ? "Підключено" : "Потребує уваги"} healthy={mailOk === true} /><Status label="Certificates" value={`${certificates.filter((item) => item.isActive).length} активних шаблонів`} healthy /></div></Surface><Surface className="bg-[#fff8ec] dark:border-[#ff8c00]/20 dark:bg-[#ff8c00]/[.07]"><Label tone="text-[#d97706]">Швидкі дії</Label><div className="mt-5 space-y-2"><Quick label="Перейти до модерації" onClick={() => setTab("content")} /><Quick label="Відкрити звернення" onClick={() => setTab("support")} /><Quick label="Налаштувати maintenance" onClick={() => setTab("maintenance")} /></div></Surface></div></>}
      {tab === "people" && <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Surface><div className="flex items-start justify-between gap-4"><div><Label>Користувачі</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Люди на платформі</h2></div><button onClick={() => setShowCreateUser(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#00c96d] px-4 py-2.5 text-sm font-semibold text-[#062112]"><UserRoundPlus className="h-4 w-4" />Додати</button></div><div className="mt-5 divide-y divide-[#152219]/8 dark:divide-white/8">{users.slice(0, 12).map((user) => <div key={user.id} className="flex items-center justify-between gap-3 py-3"><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#e8f6ed] text-sm font-bold text-[#147b47] dark:bg-[#00ff88]/10 dark:text-[#62ecaa]">{user.username.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><div className="truncate font-semibold">{user.firstName || user.username}</div><div className="truncate text-sm text-[#708075] dark:text-[#a4b2a7]">{user.email || user.username}</div></div></div><span className="rounded-lg bg-[#f2f5f2] px-2.5 py-1 text-xs font-semibold text-[#64736a] dark:bg-white/[.06] dark:text-[#a5b4a8]">{user.role}</span></div>)}</div></Surface><Surface><Label>Навчальна структура</Label><div className="mt-5 grid grid-cols-2 gap-3"><Metric value={usersByRole.teachers} label="викладачів у вибірці" /><Metric value={usersByRole.admins} label="адміністраторів" /></div><div className="mt-5 space-y-2">{classes.slice(0, 6).map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-[#f5f8f5] px-3 py-3 text-sm dark:bg-white/[.04]"><span className="font-semibold">{item.name}</span><span className="text-[#728176] dark:text-[#a4b2a7]">{item.teacherName}</span></div>)}</div></Surface></div>}
      {tab === "content" && <div className="grid gap-5 xl:grid-cols-[.78fr_1.22fr]"><Surface><Label>Навчальні матеріали</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Теми Python</h2><div className="mt-5 space-y-2">{topics.slice(0, 9).map((topic) => <div key={topic.id} className="rounded-xl bg-[#f5f8f5] p-3 dark:bg-white/[.04]"><div className="font-semibold">{topic.order}. {topic.title}</div><div className="mt-1 text-sm text-[#728176] dark:text-[#a4b2a7]">{topic.theoryBlock ? `Theory v${topic.theoryBlock.version}` : "Без теоретичного блоку"}</div></div>)}</div></Surface><Surface><div className="flex items-start justify-between gap-4"><div><Label tone="text-[#d97706]">Модерація</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Бібліотека задач</h2></div><select value={libraryStatus} onChange={(event) => setLibraryStatus(event.target.value as typeof libraryStatus)} className="rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-3 py-2 text-sm font-semibold outline-none dark:border-white/10 dark:bg-white/[.04]"><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="DRAFT">Draft</option></select></div><div className="mt-5 space-y-3">{library.map((task) => <div key={task.id} className="rounded-2xl border border-[#152219]/8 bg-[#fafcf9] p-4 dark:border-white/8 dark:bg-white/[.025]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{task.title}</div><div className="mt-1 text-sm text-[#728176] dark:text-[#a4b2a7]">{task.lang} · {task.author?.username || "Unknown author"}</div></div>{task.status === "PENDING" && <div className="flex gap-2"><button disabled={busyId === task.id} onClick={() => moderate(task, "approve")} className="rounded-lg bg-[#e5f8eb] px-3 py-2 text-xs font-semibold text-[#147b47] dark:bg-[#00ff88]/10 dark:text-[#62ecaa]">Прийняти</button><button disabled={busyId === task.id} onClick={() => moderate(task, "reject")} className="rounded-lg bg-[#fff0f4] px-3 py-2 text-xs font-semibold text-[#c44067] dark:bg-[#ff6b9d]/10 dark:text-[#ff9ab8]">Відхилити</button></div>}</div></div>)}</div></Surface></div>}
      {tab === "support" && <Surface><div className="flex items-start justify-between"><div><Label>Підтримка</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Діалоги, що потребують відповіді</h2></div><span className="rounded-xl bg-[#e8f6ed] px-3 py-2 text-sm font-semibold text-[#147b47] dark:bg-[#00ff88]/10 dark:text-[#62ecaa]">{conversations.filter((item) => item.status === "OPEN").length} open</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{conversations.map((item) => <article key={item.id} className="rounded-2xl border border-[#152219]/8 bg-[#fafcf9] p-4 dark:border-white/8 dark:bg-white/[.025]"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="truncate font-semibold">{item.subject}</div><div className="mt-1 truncate text-sm text-[#728176] dark:text-[#a4b2a7]">{item.userEmail}</div></div><span className={`h-2.5 w-2.5 rounded-full ${item.status === "OPEN" ? "bg-[#00c96d]" : "bg-[#c5cec6]"}`} /></div><div className="mt-4 text-xs text-[#85948a]">{new Date(item.lastMessageAt).toLocaleString()}</div></article>)}</div></Surface>}
      {tab === "maintenance" && <Surface><Label tone="text-[#d97706]">Maintenance</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Стан платформи</h2><div className={`mt-5 rounded-2xl p-5 ${maintenance?.enabled ? "bg-[#fff0f4] dark:bg-[#ff6b9d]/10" : "bg-[#e9f8ee] dark:bg-[#00ff88]/10"}`}><div className="flex items-center gap-3"><CircleDot className={`h-5 w-5 ${maintenance?.enabled ? "text-[#d64168]" : "text-[#147b47] dark:text-[#62ecaa]"}`} /><div><div className="font-semibold">{maintenance?.enabled ? "Maintenance увімкнено" : "Платформа доступна"}</div><div className="mt-1 text-sm text-[#6d7b71] dark:text-[#a3b1a6]">{maintenance?.message || "Немає активних обмежень."}</div></div></div></div><button onClick={toggleMaintenance} className="mt-5 rounded-xl bg-[#17251c] px-4 py-3 text-sm font-semibold text-white dark:bg-[#edf3ef] dark:text-[#0b120e]">{maintenance?.enabled ? "Вимкнути maintenance" : "Увімкнути maintenance"}</button></Surface>}
      {tab === "broadcast" && <Surface><Label>Розсилки</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Підготувати повідомлення</h2><form onSubmit={sendBroadcast} className="mt-5 max-w-2xl space-y-3"><input value={broadcast.subject} onChange={(event) => setBroadcast({ ...broadcast, subject: event.target.value })} placeholder="Тема листа" className="w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><input value={broadcast.title} onChange={(event) => setBroadcast({ ...broadcast, title: event.target.value })} placeholder="Заголовок повідомлення" className="w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><textarea value={broadcast.content} onChange={(event) => setBroadcast({ ...broadcast, content: event.target.value })} placeholder="Текст повідомлення" rows={6} className="w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><button className="inline-flex items-center gap-2 rounded-xl bg-[#00c96d] px-4 py-3 text-sm font-semibold text-[#062112]"><Send className="h-4 w-4" />Перевірити аудиторію</button>{broadcastResult && <p className="text-sm font-medium text-[#147b47] dark:text-[#62ecaa]">{broadcastResult}</p>}</form></Surface>}
      {tab === "mailbox" && <Surface><Label>Mailbox</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Підключення адміністраторської пошти</h2><div className={`mt-5 max-w-xl rounded-2xl p-5 ${mailOk ? "bg-[#e9f8ee] dark:bg-[#00ff88]/10" : "bg-[#fff0f4] dark:bg-[#ff6b9d]/10"}`}><div className="font-semibold">{mailOk ? "Mailbox підключено" : "Mailbox потребує перевірки"}</div><p className="mt-2 text-sm leading-6 text-[#6d7b71] dark:text-[#a3b1a6]">Стан визначається реальним API адміністративної пошти.</p></div></Surface>}
      {tab === "certificates" && <Surface><Label>Сертифікати</Label><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Шаблони сертифікатів</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{certificates.map((item) => <article key={item.id} className="rounded-2xl border border-[#152219]/8 bg-[#fafcf9] p-4 dark:border-white/8 dark:bg-white/[.025]"><div className="font-semibold">{item.name}</div><div className="mt-2 text-sm text-[#728176] dark:text-[#a4b2a7]">{item.isActive ? "Активний шаблон" : "Чернетка або вимкнений"}</div></article>)}</div></Surface>}
    </div>}
    {showCreateUser && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#07110b]/55 p-4 backdrop-blur-sm"><form onSubmit={createUser} className="w-full max-w-md rounded-[26px] bg-white p-6 text-[#142017] shadow-2xl dark:bg-[#121b15] dark:text-[#edf3ef]"><div className="flex items-center justify-between"><div><Label>Новий користувач</Label><h2 className="mt-2 text-xl font-semibold">Створити доступ</h2></div><button type="button" onClick={() => setShowCreateUser(false)}><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-3"><input required value={newUser.username} onChange={(event) => setNewUser({ ...newUser, username: event.target.value })} placeholder="Username" className="w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><input value={newUser.email} onChange={(event) => setNewUser({ ...newUser, email: event.target.value })} placeholder="Email" className="w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><input required type="password" value={newUser.password} onChange={(event) => setNewUser({ ...newUser, password: event.target.value })} placeholder="Пароль" className="w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><div className="grid grid-cols-2 gap-3"><select value={newUser.role} onChange={(event) => setNewUser({ ...newUser, role: event.target.value as typeof newUser.role })} className="rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-3 py-3 text-sm outline-none dark:border-white/10 dark:bg-white/[.035]"><option value="USER">User</option><option value="TEACHER">Teacher</option><option value="SYSTEM_ADMIN">Admin</option></select><select value={newUser.userMode} onChange={(event) => setNewUser({ ...newUser, userMode: event.target.value as typeof newUser.userMode })} className="rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-3 py-3 text-sm outline-none dark:border-white/10 dark:bg-white/[.035]"><option value="PERSONAL">Personal</option><option value="EDUCATIONAL">Educational</option><option value="CONTEST">Contest</option></select></div></div><button className="mt-5 w-full rounded-xl bg-[#00c96d] px-4 py-3 text-sm font-semibold text-[#062112]">Створити користувача</button></form></div>}
  </div></div>;
};

const Metric: React.FC<{ value: React.ReactNode; label: string; tone?: string }> = ({ value, label, tone = "text-[#142017] dark:text-[#edf3ef]" }) => <Surface className="p-4"><div className={`text-3xl font-semibold tracking-[-.06em] ${tone}`}>{value}</div><div className="mt-1 text-sm text-[#6d7c71] dark:text-[#a3b1a6]">{label}</div></Surface>;
const Status: React.FC<{ label: string; value: string; healthy?: boolean }> = ({ label, value, healthy = false }) => <div className="rounded-2xl bg-[#f5f8f5] p-4 dark:bg-white/[.04]"><div className="flex items-center gap-2 text-sm font-semibold"><span className={`h-2.5 w-2.5 rounded-full ${healthy ? "bg-[#00c96d]" : "bg-[#ff8c00]"}`} />{label}</div><div className="mt-3 text-sm text-[#708075] dark:text-[#a4b2a7]">{value}</div></div>;
const Quick: React.FC<{ label: string; onClick: () => void }> = ({ label, onClick }) => <button onClick={onClick} className="flex w-full items-center justify-between rounded-xl bg-white/70 px-4 py-3 text-left text-sm font-semibold text-[#4c5c50] transition hover:bg-white dark:bg-white/[.05] dark:text-[#dce8de] dark:hover:bg-white/[.1]"><span>{label}</span><ChevronRight className="h-4 w-4" /></button>;
