export * from "./AdminDashboardPage";
export * from "./CookiePolicyPage";
export * from "./DevEditorPage";
export * from "./DocsPage";
export * from "./MaintenancePage";
export * from "./PrivacyPolicyPage";
export * from "./SupportPage";
export * from "./TermsOfUsePage";
export * from "./TheoryPage";
export { default as MaintenancePage } from "./MaintenancePage";
export type { MaintenancePayload } from "./MaintenancePage";
