import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, ClipboardCheck, Plus, Users } from "lucide-react";
import { createClass, getClasses, getPendingReviews, type Class, type PendingReview } from "../../lib/api/edu";

export const TeacherWorkspacePage: React.FC = () => {
  const navigate = useNavigate();
  const isPreview = import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "true";
  const [classes, setClasses] = useState<Class[]>([]);
  const [reviews, setReviews] = useState<PendingReview[]>([]);
  const [loading, setLoading] = useState(true);
  const [openCreate, setOpenCreate] = useState(false);
  const [name, setName] = useState("");
  const [language, setLanguage] = useState<"JAVA" | "PYTHON" | "CPP">("PYTHON");
  const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const [nextClasses, nextReviews] = await Promise.all([getClasses(), getPendingReviews()]); setClasses(nextClasses); setReviews(nextReviews.pendingReviews || []); } catch (cause: any) { if (isPreview) { setClasses([{ id: -31, name: "10-Б · Python", language: "PYTHON", gradingSystem: "POINTS_12", studentsCount: 24, createdAt: "2026-07-01" }, { id: -32, name: "9-А · Основи коду", language: "PYTHON", gradingSystem: "POINTS_12", studentsCount: 19, createdAt: "2026-07-01" }]); setReviews([{ gradeId: -11, student: { id: 1, firstName: "Софія", lastName: "Мельник", email: "" }, task: { id: 501, title: "Колекції та зрізи", lesson: { id: -31, title: "10-Б · Python", type: "LESSON" } }, submittedCode: "print('ok')", submittedAt: new Date().toISOString(), system: "new" }, { gradeId: -12, student: { id: 2, firstName: "Марко", lastName: "Литвин", email: "" }, task: { id: 502, title: "Функції з характером", lesson: { id: -31, title: "10-Б · Python", type: "LESSON" } }, submittedCode: "def solve(): pass", submittedAt: new Date().toISOString(), system: "new" }]); } else setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося завантажити простір викладача.")); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await createClass(name, language); setName(""); setOpenCreate(false); await load(); } catch (cause: any) { setError(String(cause?.response?.data?.message || cause?.message || "Не вдалося створити клас.")); } };
  return <div className="min-h-full bg-[#f7f8f5] px-4 py-7 text-[#142017] dark:bg-[#0b120e] dark:text-[#edf3ef] sm:px-6 lg:px-10 lg:py-10"><div className="mx-auto max-w-7xl space-y-6">
    <section className="rounded-[28px] bg-[#183023] p-6 text-white shadow-[0_24px_58px_-38px_rgba(4,24,12,.8)] sm:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="text-xs font-semibold uppercase tracking-[.16em] text-[#72edb0]">Teaching workspace</div><h1 className="mt-4 font-[family-name:var(--font-display)] text-3xl font-bold tracking-[-.055em] sm:text-5xl">Клас у фокусі.<br />Рішення під контролем.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#bed1c0]">Плануй уроки, бач прогрес учнів та повертай фідбек саме тоді, коли він потрібен.</p></div><button type="button" onClick={() => setOpenCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#eff6f0] px-4 py-3 text-sm font-semibold text-[#102117]"><Plus className="h-4 w-4" />Новий клас</button></div></section>
    {error && <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#fff0f4] p-4 text-sm text-[#bd3c62] dark:bg-[#ff6b9d]/10 dark:text-[#ffa5bf]" role="alert"><span>{error}</span><button type="button" onClick={() => void load()} className="rounded-xl border border-current px-3 py-2 text-xs font-bold">Повторити</button></div>}
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[24px] border border-[#152219]/10 bg-white p-5 dark:border-white/10 dark:bg-[#121b15]"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.16em] text-[#147b47] dark:text-[#62ecaa]">Класи</div><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Навчальні потоки</h2></div><span className="rounded-xl bg-[#e9f8ee] px-3 py-2 text-sm font-semibold text-[#147b47] dark:bg-[#00ff88]/10 dark:text-[#62ecaa]">{classes.length}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{loading ? Array.from({ length: 4 }, (_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-[#edf2ee] dark:bg-white/[.045]" />) : classes.map((item) => <button type="button" key={item.id} onClick={() => navigate(`/edu/classes/${item.id}`)} className="group rounded-2xl border border-[#152219]/8 bg-[#fafcf9] p-4 text-left transition hover:-translate-y-0.5 hover:border-[#00c96d]/40 dark:border-white/8 dark:bg-white/[.025]"><div className="flex items-start justify-between"><span className="rounded-lg bg-[#e8f6ed] px-2.5 py-1 text-xs font-semibold text-[#147b47] dark:bg-[#00ff88]/10 dark:text-[#62ecaa]">{item.language}</span><ArrowRight className="h-4 w-4 text-[#789086] transition group-hover:translate-x-1" /></div><div className="mt-5 text-lg font-semibold">{item.name}</div><div className="mt-2 flex items-center gap-2 text-sm text-[#718075] dark:text-[#a4b2a7]"><Users className="h-4 w-4" />{item.studentsCount} учнів</div></button>)}</div></section>
      <section className="rounded-[24px] border border-[#152219]/10 bg-[#fff8ec] p-5 dark:border-[#ff8c00]/20 dark:bg-[#ff8c00]/[.07]"><div className="text-xs font-semibold uppercase tracking-[.16em] text-[#d97706]">Черга фідбеку</div><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Рішення чекають</h2><div className="mt-5 space-y-3">{reviews.slice(0, 5).map((review) => <button type="button" key={review.gradeId} disabled={!review.classId} onClick={() => { if (review.classId) navigate(`/edu/classes/${review.classId}`); }} className="flex w-full items-center justify-between rounded-xl bg-white/70 p-3 text-left transition enabled:hover:bg-white dark:bg-white/[.06] disabled:cursor-default disabled:opacity-70"><div><div className="font-semibold">{review.task?.title || `Робота #${review.gradeId}`}</div><div className="mt-1 text-sm text-[#776e5d] dark:text-[#c2b08e]">{review.student.firstName} {review.student.lastName} · {review.className || review.task?.lesson?.title || "ручна перевірка"}</div></div><ClipboardCheck className="h-4 w-4 text-[#d97706]" /></button>)}{!loading && reviews.length === 0 && <div className="rounded-xl bg-white/70 p-4 text-sm text-[#776e5d] dark:bg-white/[.06] dark:text-[#c2b08e]">Черга чиста — чудовий момент підготувати наступний урок.</div>}</div></section></div>
    {openCreate && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#06110a]/55 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-md rounded-[26px] bg-white p-6 shadow-2xl dark:bg-[#121b15]"><div className="text-xs font-semibold uppercase tracking-[.16em] text-[#147b47] dark:text-[#62ecaa]">Новий клас</div><h2 className="mt-2 text-2xl font-semibold">Почнімо новий потік</h2><input autoFocus required value={name} onChange={(event) => setName(event.target.value)} placeholder="Назва класу" className="mt-5 w-full rounded-xl border border-[#152219]/10 bg-[#fafcf9] px-4 py-3 text-sm outline-none focus:border-[#00c96d] dark:border-white/10 dark:bg-white/[.035]" /><div className="mt-3 grid grid-cols-3 gap-2">{(["PYTHON", "JAVA", "CPP"] as const).map((item) => <button type="button" key={item} onClick={() => setLanguage(item)} className={`rounded-xl px-3 py-3 text-sm font-semibold ${language === item ? "bg-[#17251c] text-white dark:bg-[#edf3ef] dark:text-[#0b120e]" : "bg-[#f2f5f2] text-[#68776d] dark:bg-white/[.06] dark:text-[#a5b4a8]"}`}>{item === "CPP" ? "C++" : item}</button>)}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setOpenCreate(false)} className="rounded-xl px-4 py-3 text-sm font-semibold">Скасувати</button><button className="rounded-xl bg-[#00c96d] px-4 py-3 text-sm font-semibold text-[#062112]">Створити клас</button></div></form></div>}
  </div></div>;
};
